/* import React, { useState } from "react"; */
import useOnClickOutside from "@/app/utils/useOutsideClick";
import { useRef, useState } from "react";
import { Dropdown, DropdownButton } from "react-bootstrap";
// Country codes data

// Full list of countries with codes
const countryCodes = [
	{ name: "AFG", code: "+93" },
	{ name: "AGO", code: "+244" },
	{ name: "ALB", code: "+355" },
	{ name: "AND", code: "+376" },
	{ name: "ARE", code: "+971" },
	{ name: "ARG", code: "+54" },
	{ name: "ARM", code: "+374" },
	{ name: "ATG", code: "+1-268" },
	{ name: "AUS", code: "+61" },
	{ name: "AUT", code: "+43" },
	{ name: "AZE", code: "+994" },
	{ name: "BDI", code: "+257" },
	{ name: "BEL", code: "+32" },
	{ name: "BEN", code: "+229" },
	{ name: "BFA", code: "+226" },
	{ name: "BGD", code: "+880" },
	{ name: "BGR", code: "+359" },
	{ name: "BHR", code: "+973" },
	{ name: "BHS", code: "+1-242" },
	{ name: "BIH", code: "+387" },
	{ name: "BLR", code: "+375" },
	{ name: "BLZ", code: "+501" },
	{ name: "BOL", code: "+591" },
	{ name: "BRA", code: "+55" },
	{ name: "BRB", code: "+1-246" },
	{ name: "BRN", code: "+673" },
	{ name: "BTN", code: "+975" },
	{ name: "BWA", code: "+267" },
	{ name: "CAF", code: "+236" },
	{ name: "CAN", code: "+1" },
	{ name: "CHE", code: "+41" },
	{ name: "CHL", code: "+56" },
	{ name: "CHN", code: "+86" },
	{ name: "CIV", code: "+225" },
	{ name: "CMR", code: "+237" },
	{ name: "COD", code: "+243" },
	{ name: "COG", code: "+242" },
	{ name: "COL", code: "+57" },
	{ name: "COM", code: "+269" },
	{ name: "CPV", code: "+238" },
	{ name: "CRI", code: "+506" },
	{ name: "CUB", code: "+53" },
	{ name: "CYP", code: "+357" },
	{ name: "CZE", code: "+420" },
	{ name: "DEU", code: "+49" },
	{ name: "DJI", code: "+253" },
	{ name: "DMA", code: "+1-767" },
	{ name: "DNK", code: "+45" },
	{ name: "DOM", code: "+1-809" },
	{ name: "DZA", code: "+213" },
	{ name: "ECU", code: "+593" },
	{ name: "EGY", code: "+20" },
	{ name: "ERI", code: "+291" },
	{ name: "ESP", code: "+34" },
	{ name: "EST", code: "+372" },
	{ name: "ETH", code: "+251" },
	{ name: "FIN", code: "+358" },
	{ name: "FJI", code: "+679" },
	{ name: "FRA", code: "+33" },
	{ name: "FSM", code: "+691" },
	{ name: "GAB", code: "+241" },
	{ name: "GBR", code: "+44" },
	{ name: "GEO", code: "+995" },
	{ name: "GHA", code: "+233" },
	{ name: "GIN", code: "+224" },
	{ name: "GMB", code: "+220" },
	{ name: "GNB", code: "+245" },
	{ name: "GNQ", code: "+240" },
	{ name: "GRC", code: "+30" },
	{ name: "GRD", code: "+1-473" },
	{ name: "GTM", code: "+502" },
	{ name: "GUY", code: "+592" },
	{ name: "HND", code: "+504" },
	{ name: "HRV", code: "+385" },
	{ name: "HTI", code: "+509" },
	{ name: "HUN", code: "+36" },
	{ name: "IDN", code: "+62" },
	{ name: "IND", code: "+91" },
	{ name: "IRL", code: "+353" },
	{ name: "IRN", code: "+98" },
	{ name: "IRQ", code: "+964" },
	{ name: "ISL", code: "+354" },
	{ name: "ISR", code: "+972" },
	{ name: "ITA", code: "+39" },
	{ name: "JAM", code: "+1-876" },
	{ name: "JOR", code: "+962" },
	{ name: "JPN", code: "+81" },
	{ name: "KAZ", code: "+7" },
	{ name: "KEN", code: "+254" },
	{ name: "KGZ", code: "+996" },
	{ name: "KHM", code: "+855" },
	{ name: "KIR", code: "+686" },
	{ name: "KNA", code: "+1-869" },
	{ name: "KOR", code: "+82" },
	{ name: "KWT", code: "+965" },
	{ name: "LAO", code: "+856" },
	{ name: "LBN", code: "+961" },
	{ name: "LBR", code: "+231" },
	{ name: "LBY", code: "+218" },
	{ name: "LCA", code: "+1-758" },
	{ name: "LIE", code: "+423" },
	{ name: "LKA", code: "+94" },
	{ name: "LSO", code: "+266" },
	{ name: "LTU", code: "+370" },
	{ name: "LUX", code: "+352" },
	{ name: "LVA", code: "+371" },
	{ name: "MAR", code: "+212" },
	{ name: "MCO", code: "+377" },
	{ name: "MDA", code: "+373" },
	{ name: "MDG", code: "+261" },
	{ name: "MDV", code: "+960" },
	{ name: "MEX", code: "+52" },
	{ name: "MHL", code: "+692" },
	{ name: "MKD", code: "+389" },
	{ name: "MLI", code: "+223" },
	{ name: "MLT", code: "+356" },
	{ name: "MMR", code: "+95" },
	{ name: "MNE", code: "+382" },
	{ name: "MNG", code: "+976" },
	{ name: "MOZ", code: "+258" },
	{ name: "MRT", code: "+222" },
	{ name: "MUS", code: "+230" },
	{ name: "MWI", code: "+265" },
	{ name: "MYS", code: "+60" },
	{ name: "NAM", code: "+264" },
	{ name: "NER", code: "+227" },
	{ name: "NGA", code: "+234" },
	{ name: "NIC", code: "+505" },
	{ name: "NLD", code: "+31" },
	{ name: "NOR", code: "+47" },
	{ name: "NPL", code: "+977" },
	{ name: "NRU", code: "+674" },
	{ name: "NZL", code: "+64" },
	{ name: "OMN", code: "+968" },
	{ name: "PAK", code: "+92" },
	{ name: "PAN", code: "+507" },
	{ name: "PER", code: "+51" },
	{ name: "PHL", code: "+63" },
	{ name: "PLW", code: "+680" },
	{ name: "PNG", code: "+675" },
	{ name: "POL", code: "+48" },
	{ name: "PRT", code: "+351" },
	{ name: "PRY", code: "+595" },
	{ name: "QAT", code: "+974" },
	{ name: "ROU", code: "+40" },
	{ name: "RUS", code: "+7" },
	{ name: "RWA", code: "+250" },
	{ name: "SAU", code: "+966" },
	{ name: "SDN", code: "+249" },
	{ name: "SEN", code: "+221" },
	{ name: "SGP", code: "+65" },
	{ name: "SLE", code: "+232" },
	{ name: "SLV", code: "+503" },
	{ name: "SMR", code: "+378" },
	{ name: "SOM", code: "+252" },
	{ name: "SRB", code: "+381" },
	{ name: "STP", code: "+239" },
	{ name: "SUR", code: "+597" },
	{ name: "SVK", code: "+421" },
	{ name: "SVN", code: "+386" },
	{ name: "SWE", code: "+46" },
	{ name: "SWZ", code: "+268" },
	{ name: "SYC", code: "+248" },
	{ name: "SYR", code: "+963" },
	{ name: "TCD", code: "+235" },
	{ name: "TGO", code: "+228" },
	{ name: "THA", code: "+66" },
	{ name: "TJK", code: "+992" },
	{ name: "TKM", code: "+993" },
	{ name: "TLS", code: "+670" },
	{ name: "TON", code: "+676" },
	{ name: "TTO", code: "+1-868" },
	{ name: "TUN", code: "+216" },
	{ name: "TUR", code: "+90" },
	{ name: "TUV", code: "+688" },
	{ name: "TWN", code: "+886" },
	{ name: "TZA", code: "+255" },
	{ name: "UGA", code: "+256" },
	{ name: "UKR", code: "+380" },
	{ name: "URY", code: "+598" },
	{ name: "USA", code: "+1" },
	{ name: "UZB", code: "+998" },
	{ name: "VAT", code: "+379" },
	{ name: "VCT", code: "+1-784" },
	{ name: "VEN", code: "+58" },
	{ name: "VNM", code: "+84" },
	{ name: "VUT", code: "+678" },
	{ name: "WSM", code: "+685" },
	{ name: "YEM", code: "+967" },
	{ name: "ZAF", code: "+27" },
	{ name: "ZMB", code: "+260" },
	{ name: "ZWE", code: "+263" },
];

const CountryCodeSelector = ({ selectedCode, handleSelect }) => {
	const [isClicked, setIsClicked] = useState(false)
	const buttonRef = useRef()
	useOnClickOutside(buttonRef, () => setIsClicked(false), [])
	return (
		<div>
			<DropdownButton
				ref={buttonRef}
				style={{ zIndex: isClicked ? '999999' : '9999' }}
				className="dropdown-2"
				id="country-code-dropdown"
				title={selectedCode}
				onClick={(e) => { setIsClicked(!e.target.classList.contains('show')) }}
				onSelect={handleSelect}>
				{countryCodes.map((country, index) => (
					<Dropdown.Item
						key={index}
						eventKey={`${country.name} ${country.code}`}>
						{country.name} {country.code}
					</Dropdown.Item>
				))}
			</DropdownButton>
		</div>
	);
};

export default CountryCodeSelector;
